### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by umutzd** [punkave/apostrophe-pieces-submit-widgets#11]
I try to extend this module so that I can build a `request information` form. 

My app.js: 
```js
    'info': {},
    'info-submit-widgets': {},
```

/lib/modules/info/index.js:
```js
module.exports = {
    extends: 'apostrophe-pieces',
    name: 'info',
    addFields: [
        {
            name: 'name',
            label: 'Name',
            type: 'string',
            required: true
        },
      ]
}
```

/lib/modules/info-submit-widgets/index.js:
```js
module.exports = {
    extend: 'apostrophe-pieces-submit-widgets',
    name: 'info-submit',
    fields: [ 'name' ]
};
```

And the error: 

```js
TypeError: Cannot read property 'length' of undefined
    at Object.self.subset (/node_modules/apostrophe/lib/modules/apostrophe-schemas/index.js:331:19)
    at Object.self.setSubmitSchema (/node_modules/apostrophe-pieces-submit-widgets/index.js:29:47)
    at afterConstruct (/node_modules/apostrophe-pieces-submit-widgets/index.js:19:10)
    at afterConstruct (/node_modules/moog/index.js:302:21)
    at /node_modules/moog/index.js:312:22
    at /node_modules/async/lib/async.js:181:20
    at iterate (/node_modules/async/lib/async.js:262:13)
    at Immediate.<anonymous> (/node_modules/async/lib/async.js:274:29)
    at Immediate.<anonymous> (/node_modules/async/lib/async.js:44:16)
    at processImmediate (timers.js:632:19)
```

**Comment by umutzd** [comment]
Solved by realizing that I used property `extends` instead of `extend`
